### ISSUE TITLE
problem/question about AFURLConnectionByteSpeedMeasure

### ISSUE THREAD

**Issue by linkos882** [OliverLetterer/AFURLConnectionByteSpeedMeasure#1]
hi, im using AFNetworking on my iPad project application for downloading some files. it work great and now I want to add the ability to monitor speed download with your AFURLConnection speed measure but I have a problem  

i've included the 4 files from the zip file into my project but I've some warning error on the "AFURLConnectionOperation+AFURLConnectionByteSpeedMeasure.m" file.

I add a screenshot so, you can see what I'm talking about. 

Do you think you could help me with my issues? Sorry for my english, I'm french.

LinKoS

![Capture d e cran 2013-02-02 a 15 33 58](https://f.cloud.github.com/assets/3457143/120864/90cfacbe-6d47-11e2-9e7e-36e4e32cb2f7.png)

**Comment by OliverLetterer** [comment]
Looks like i forgot to include `#import <objc/runtime.h>` which was in my pch file.
