### ISSUE TITLE
retain cycle of *operation in AFURLConnectionByteSpeedMeasure

### ISSUE THREAD

**Issue by ghost** [OliverLetterer/AFURLConnectionByteSpeedMeasure#2]
Hi there,

I'm a very newbie in IOS. I am going to develop a easy app to measure the download/upload speed and show the calculation on the label text.
My platform is IOS6, AFNetworking-master and AFURLConnectionByteSpeedMeasure-master are downloaded, managed by cocoapods.

The problem is , it leads to retain cycle while I copy the sample code into my project.
Warning shows "Capturing 'operation' strongly in this block is licke to lead to a retain cycle".

I know there's a comment above says that need to pass a weak reference to operation into the progress block, but not sure how to do.

Does the code make sense for the purpose?
Can someone help?
Very appreciate!!

![2013-05-18 3 07 05](https://f.cloud.github.com/assets/4452878/519893/020894b6-bf25-11e2-95b3-698f3666d90f.png)

**Comment by OliverLetterer** [comment]
Breaking the retain cycle can be done with:

``` objc
NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"http://download.thinkbroadband.com/1GB.zip"]];
AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
operation.downloadSpeedMeasure.active = YES;

__weak AFHTTPRequestOperation *weakOperation = nil;
[operation setDownloadProgressBlock:^(NSUInteger bytesRead, long long totalBytesRead, long long totalBytesExpectedToRead) {
    AFHTTPRequestOperation *strongOperation = weakOperation;
    double speedInBytesPerSecond = strongOperation.downloadSpeedMeasure.speed;
    NSString *humanReadableSpeed = strongOperation.downloadSpeedMeasure.humanReadableSpeed;

    NSTimeInterval remainingTimeInSeconds = [strongOperation.downloadSpeedMeasure remainingTimeOfTotalSize:totalBytesExpectedToRead numberOfCompletedBytes:totalBytesRead];
    NSString *humanReadableRemaingTime = [strongOperation.downloadSpeedMeasure humanReadableRemainingTimeOfTotalSize:totalBytesExpectedToRead numberOfCompletedBytes:totalBytesRead];
}];
```

I would encourage you to read more about retain cycles since they are very common under arc.

**Comment by ghost** [comment]
Thank so much, Oliver, the warning disappear.

One more stupid question, I'm going to print the result on the label, so use setText as below code, but the label text does not work in the simulator.
- (IBAction)btn:(id)sender
  {
  [self.label2 setText:@"aaa"];
  ...
  ....etc
      NSString *humanReadableSpeed = strongOperation.downloadSpeedMeasure.humanReadableSpeed;
  
  ```
   // Print the measurement result 
  [self.label2 setText:humanReadableSpeed];
  ```
  
  }];
  }
