### ISSUE TITLE
The result of download speed calculation is not accurate.

### ISSUE THREAD

**Issue by ghost** [OliverLetterer/AFURLConnectionByteSpeedMeasure#3]
Hi there,

Thanks for the extension of AFURLconnectionBytesppedMeasure, it works well for me.
But I found a problem in terms of the download speed result.

```
NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"http://tpdb.speed2.hinet.net/test_010m.zip"]];
```

 NSString *humanReadableSpeed =strongOperation.downloadSpeedMeasure.humanReadableSpeed;

When I print out (NSLog) the humanReadableSpeed, is like 1.56MB, but if I head to speedtesting website (e.g.http://speed2.hinet.net/do.aspx), the download speed is like 14MB, is there any known issue of this?

**Comment by OliverLetterer** [comment]
AFURLconnectionByteSpeedMeasure calculates the average speed over the last x times the NSURLConnection has received any data. To smooth this data, a window with a given size is being used. You can try and configure the windowSize of the corresponding AFURLconnectionByteSpeedMeasure to meet you needs. If you are on a fast network with 14MB/s this 10MB file would be downloaded in under 1 second. That is pretty steep and might get smoothed out by the window.
