### ISSUE TITLE
AFURLConnectionOperation.h not found

### ISSUE THREAD

**Issue by ghost** [OliverLetterer/AFURLConnectionByteSpeedMeasure#5]
Hey,

I tried to integrate AFURLConnectionByteSpeedMeasure using cocoapod and got this error. I have added AFNetworking to my project using cocoapod only. Could you please let me know a better solution?

Thanks

**Comment by ghost** [comment]
changed #import "AFURLConnectionOperation.h" to
#import <AFNetworking/AFURLConnectionOperation.h> , issue got solved.

**Comment by Prakashrastogi** [comment]
Hi,
I have updated my AFNetworking API to latest version (greater than v3) through pod but still getting error AFURLConnectionOperation.h not found. AFURLConnectionOperation.h class is missing in API.
Please guide me.
